sudo: required

services:
  - docker

before_install:
  - "docker build -t sunkor/fibonacci-stack-react-test -f Dockerfile.dev ./client/Dockerfile.dev"

script:
  - "docker run -e CI=true sunkor/docker-react npm run test -- --coverage"

after_success:
  - "docker build -t sunkor/fibonacci-stack-client ./client"
  - "docker build -t sunkor/fibonacci-stack-nginx ./nginx"
  - "docker build -t sunkor/fibonacci-stack-server ./server"
  - "docker build -t sunkor/fibonacci-stack-worker ./worker"

#log-in to Docker CLI
- echo "$DOCKER_PASSWORD" | docker_login -u "$DOCKER_ID" --pasword-stdin

#Take those images and push them to docker hub
- docker push sunkor/fibonacci-stack-client
- docker push sunkor/fibonacci-stack-nginx
- docker push sunkor/fibonacci-stack-server
- docker push sunkor/fibonacci-stack-worker