sudo: required

services:
  - docker

before_install:
  - "docker build -t sunkor/fibonacci-stack-react-test -f ./frontend/Dockerfile.dev ./frontend"

script:
  - "docker run -e CI=true sunkor/fibonacci-stack-react-test npm run test -- --coverage"

after_success:
  - docker build -t sunkor/fibonacci-stack-frontend ./frontend
  - docker build -t sunkor/fibonacci-stack-nginx ./nginx
  - docker build -t sunkor/fibonacci-stack-server ./server
  - docker build -t sunkor/fibonacci-stack-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sunkor/fibonacci-stack-frontend
  - docker push sunkor/fibonacci-stack-nginx
  - docker push sunkor/fibonacci-stack-server
  - docker push sunkor/fibonacci-stack-worker
# deploy:
#   provider: elasticbeanstalk
#   region: ap-southeast-2
#   app: docker-fibonacci
#   env: DockerFibonacci-env
#   bucket_name: elasticbeanstalk-ap-southeast-2-068004728410
#   bucket_path: docker-fibonacci
#   on:
#     branch: master
#   access_key_id:
#     secure: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
